### ISSUE TITLE
TV channel error Ziggo sport

### ISSUE THREAD

**Issue by sven41** [Sholofly/arrisdcx960#1] opened 2021-08-30 20:53 UTC
I install the code but the problem don't solve..  TV` channel 14 Ziggo sport does not provide the information available

![117196810-42851280-ade7-11eb-98b9-31be25023fd1](https://user-images.githubusercontent.com/60574634/131404317-42fe16a2-8fe3-4f70-a657-8808f705cd08.png)

![foto](https://user-images.githubusercontent.com/60574634/131404174-99a5cda2-395b-44e2-a0d3-ee9ebfe5b29a.JPG)

**Comment by Sholofly** [comment] 2021-09-01 12:56
Please enable debug logging for the ziggonext library and post pr mail your log (please anonimize sensitive data). I will examine it to find the issue.

**Comment by golles** [comment] 2021-09-01 13:24
I had the same issue with the previous version and first thing checked after installing this one and indeed the issue is still present.
Please check the info that I logged in this issue: https://github.com/Sholofly/ZiggoNext/issues/68#issuecomment-821800271

**Comment by Sholofly** [comment] 2021-09-01 13:29
Hi @golles Thanks. It's indeed a strange issue. It looks like it can't gather the correct info for this channel. As soon as I have time I will dive into this issue. Thanks for you patience.

**Comment by golles** [comment] 2021-09-01 13:49
I remember I've looked into it earlier as well and I remember that those Ziggo channels are not in the data. I think it was also the other channels (400 range) only the public Ziggo TV (13) doesn't have this issue.
But! It is already a while ago that I checked...

**Comment by Sholofly** [comment] 2021-09-01 13:53
Does the ziggogo.tv website show images when you control the box using the site?

**Comment by sven41** [comment] 2021-09-01 15:21
> 
> 
> Does the ziggogo.tv website show images when you control the box using the site?

![afbeelding](https://user-images.githubusercontent.com/60574634/131698409-73069179-c173-4566-9b2c-1ae5b735c689.png)

**Comment by Sholofly** [comment] 2021-09-01 17:02
Is this when your channel is on 14?

**Comment by sven41** [comment] 2021-09-01 17:32
> Is this when your channel is on 14?

Yes man!

**Comment by Sholofly** [comment] 2021-09-04 12:54
I am affraid i can't help you. It looks like the info is not in your account or so...

**Comment by golles** [comment] 2021-09-04 13:10
I just double-checked and channel 401 is working fine.
Could it be that channel 14 is just a"pointer" to channel 401? From what I quickly could see is that they have the same content https://www.ziggosport.nl/programmagids/

**Comment by sven41** [comment] 2021-09-04 19:18
> I just double-checked and channel 401 is working fine.
> Could it be that channel 14 is just a"pointer" to channel 401? From what I quickly could see is that they have the same content https://www.ziggosport.nl/programmagids/

I have contacted ziggo they have never heard of the problem and I had to create a topic on their site so continued maybe it is an idea that you also respond to my topic that you have the same problem.

https://community.ziggo.nl/t5/Ziggo-GO/Ziggo-sport-14-Geen-programma-informatie/td-p/836077

**Comment by Sholofly** [comment] 2021-09-13 18:59
I subscribed to the topic but it looks like it is an issue at the Ziggo side. Therefore i will close this issue.

**Closed by Sholofly** 2021-09-13 18:59 UTC

**Comment by golles** [comment] 2021-09-13 20:53
Indeed, Ziggo should fix this. Using channel 401 and not 14 is a"workable" solution for now
