### ISSUE TITLE
Can't login anymore by Ziggo. Need an authentication code via a SMS

### ISSUE THREAD

**Issue by JanStalenburg** [Sholofly/arrisdcx960#39] opened 2022-10-14 09:54 UTC
**Describe the bug**
Can't login anymore by Ziggo. Need an authentication code via a SMS

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version of the component**
1.2.0

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    arris_dcx960: debug
```

**Additional context**

**Comment by mleenaerts** [comment] 2022-10-14 13:32
![image](https://user-images.githubusercontent.com/18590048/195859144-2dee54ac-df6f-4e85-8322-60506314d591.png)

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 69, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 350, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 344, in _do_api_call
    raise ArrisDCX960ConnectionError(
arris_dcx960.exceptions.ArrisDCX960ConnectionError: API call failed: 404`

It indeed seems to be related with the recent change of Ziggo to enforce 2FA.

**Comment by mleenaerts** [comment] 2022-10-14 17:05
I think this can be closed as duplicate of https://github.com/Sholofly/arrisdcx960/issues/38

**Comment by Sholofly** [comment] 2022-10-16 22:20
Yup, please move to https://github.com/Sholofly/lghorizon for Ziggo boxes

**Closed by Sholofly** 2022-10-16 22:20 UTC
Labels: bug
